services:
  - type: web
    name: arbitro-backend
    runtime: python
    repo: https://github.com/wilycol/Arbitro-AI
    branch: main
    buildCommand: ""
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: GITHUB_TOKEN
        sync: false
